name: Exercise Eenie-Meenie

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronized

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: npm run lint

  test-me:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: testing code
        uses: npm run test

  deploy:
    needs: [lint, build]
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: deploy
        run: echo "Deploy Meow...."
