name: Test Eenie-Meenie

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronized

jobs:
  theFirstTest:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: theFirstTest
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy
        run: echo "Deploying..."
